Feature/manage repositories
stone-payments/provider-github pull request #5
Opened 2021-07-08 13:05 UTC by Feggah

### Description of your changes
Add support for repository creation from template

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- Manual tests managing the life cycle of the repositories (CRUD)
- Unit tests

2021-07-12 21:36 UTC, cnatan requested changes

2021-07-12 21:36 UTC, cnatan commented on pkg/clients/repositories/repository.go
> +func OverrideTemplateRepoRequest(rp v1alpha1.RepositoryParameters) github.TemplateRepoRequest {
This method does not override anything since it doesn't receives a `github.TemplateRepoRequest`as a argument, but create a new one, fills it with values from the cr.spec  and return it.

Maybe we should follow the other providers patterns and call it `GenerateTemplateRepoInstance` or `GenerateTemplateRepoRequest`.

2021-07-12 21:36 UTC, cnatan commented on pkg/controller/repositories/repository_test.go
> +	}{
Missing error cases scenarios.

2021-07-12 21:38 UTC, cnatan commented
What should happens when the repository referenced at templateRef does not exits?
I got this log that looks like it's trying to create it.

`"CannotCreateExternalResource", "message": "cannot create Repository: POST https://api.github.com/repos/cnatan/provider-template-2/generate: 404 Not Found []"}`

2021-07-13 15:48 UTC, Feggah commented
> What should happens when the repository referenced at templateRef does not exits?
> I got this log that looks like it's trying to create it.
> 
> `"CannotCreateExternalResource", "message": "cannot create Repository: POST https://api.github.com/repos/cnatan/provider-template-2/generate: 404 Not Found []"}`

The API does not return a specific error when the template repository doesn't exist (print screen below)
![image](https://user-images.githubusercontent.com/11353912/125483360-daf6f973-95b7-4147-ab2c-7daa47287889.png)

To improve the user experience in this error scenario, I wrapped it with a self explanatory message: `the referenced repository template was not found`

2021-07-13 17:12 UTC, cnatan approved these changes

2021-07-13 17:46 UTC, merged