CRD GitHub repository secrets
stone-payments/provider-github pull request #7
Opened 2021-08-19 20:39 UTC by Giomaster

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2021-08-19 20:44 UTC, Giomaster commented
I try to run `make reviewable test` but i got some errors about some packages (Please, see details above to understand better the issue). Any help must be appreciate 😀

2021-08-20 11:56 UTC, G5Olivieri commented on pkg/clients/secrets/secrets.go
> +func callEncryptSecret(ctx context.Context, client client.Client, cr *v1alpha1.SecretsParameters, name string, gh Service) (*github.EncryptedSecret, string, error) {
I think it is better to rename this funtion to `setupEncryptedSecret`, because of the above description

2021-08-20 11:56 UTC, G5Olivieri commented on pkg/clients/secrets/secrets.go
> +	val, _ := resource.ExtractSecret(ctx, client, ref)
I think it's never good to ignore errors

2021-08-20 11:56 UTC, G5Olivieri commented on pkg/clients/secrets/secrets.go
> +// callEncryptedSecret setup encrypted secret and generates hash to store
The description and function name are different

2021-08-23 19:04 UTC, Feggah requested changes
I think we shouldn't change the folders structure for `fake`. Using `provider-aws` as a model, they use the `fake` folder inside each resource. We can follow this same pattern.

There is a problem with this managed resource name. We can't have two resources with the same name: the Kubernetes built-in secret and the repository secret.

If we try to use `kubectl get secret`, it won't return the repository secrets. We need to change it, so we can easily get/describe repository secrets without conflicting with K8S secrets. I was thinking in something like `githubsecret` or `ghsecret`, any thoughts?

2021-08-23 19:04 UTC, Feggah commented on apis/secrets/v1alpha1/secrets_types.go
> +	Value *xpv1.SecretKeySelector `json:"value"`
Non-optional fields in Parameters must be non-pointers.

2021-08-23 19:04 UTC, Feggah commented on apis/secrets/v1alpha1/secrets_types.go
> +	LastUpdate *string `json:"last_update,omitempty"`
Observation fields must be non-pointers.

Even though the GitHub API uses `snake_case` responses, we should stick to kubernetes-related YAML pattern, which is `camelCase`. You can see that the other resources in this repository uses `camelCase` fields.

2021-08-23 19:04 UTC, Feggah commented on apis/secrets/v1alpha1/secrets_types.go
> +// +kubebuilder:printcolumn:name="URL",type="string",JSONPath=".status.atProvider.htmlUrl"
This resource doesn't have this `JSONPath=.status.atProvider.htmlUrl`, you should remove or change it to a more representative field

2021-08-23 19:04 UTC, Feggah commented on pkg/clients/secrets/secrets.go
> +		hash = generateHash("test")
I didn't understand this line, why do we need the hash for "test"?

2021-08-23 19:04 UTC, Feggah commented on pkg/clients/secrets/secrets.go
> +	}
Instead of doing if-conditionals for each resource, Crossplane managed resources usually uses `cmp.Equal` to compare all fields at once. I know that this Observation only has 2 fields, but I think it isn't hard to implement this.

You can create a `&v1alpha1.SecretsObservation{}` struct and populate it with `hash` and `sec.UpdatedAt.String()`. Then you just compare both structs: the created one and the other received by parameter using `cmp.Equal`

2021-08-23 19:04 UTC, Feggah commented on pkg/clients/secrets/secrets.go
> +	var hash string
I think you should declare variables when you will need to use them. You are using it in line 76, I would recommend you to declare it right before this line.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +package secrets
You need to put the copyright in the beginning of this file.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +// 	errTemplateNotFound  = "the referenced Secrets template was not found"
I think you should remove the commented lines.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +			managed.WithInitializers(managed.NewDefaultProviderConfig(mgr.GetClient())),
If you are using custom initializers, you need to use `managed.NewNameAsExternalName` along with it, because if you don't, when the user applies the YAML manifest without defining the `crossplane.io/external-name`, the function `meta.GetExternalName` will return `""` (the runtime won't populate the name).

You can test this applying the manifest without the external-name annotation, it will return an error 404, even if you fill the manifest properly.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +			return managed.ExternalObservation{}, errors.Wrap(err, "Error to verify if is up to date")
I think you should add one more test case to cover this line

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +	ex := false
I'm not a huge fan of those variable names. I think you can change it to "upToDate" and "exists", this will keep the simplistic and improve the readability of the code.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +	if cr.Status.AtProvider.EncryptValue != nil {
I think if you change this conditional to an early return it will make the code less complex (you will unnest this conditional body).

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +		check, err := secrets.IsUpToDate(ctx, e.client, &cr.Spec.ForProvider, &cr.Status.AtProvider, meta.GetExternalName(cr), e.gh)
Instead of using `check` to hold the returned value of the IsUpToDate, isn't it be simpler to use directly the variable `ud`?

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +	sec, _, err := e.gh.GetRepoSecret(ctx, cr.Spec.ForProvider.Owner, cr.Spec.ForProvider.Repository, meta.GetExternalName(cr))
I think this request is not necessary. If you refactor your `CreateOrUpdateSec()` to return one more value (the secret returned by the `CreateOrUpdateRepoSecret()` SDK method) you will end up having in one request the secret creation request and the secret struct to fill the Observation fields. It will improve the reconcile time and avoid throttling at scale.

2021-08-23 19:04 UTC, Feggah commented on pkg/controller/secrets/secrets.go
> +	sec, _, err := e.gh.GetRepoSecret(ctx, cr.Spec.ForProvider.Owner, cr.Spec.ForProvider.Repository, meta.GetExternalName(cr))
This is the same that I commented in the `Create()` method

2021-08-23 20:05 UTC, Giomaster commented on pkg/clients/secrets/secrets.go
> +		hash = generateHash("test")
My apologize for this, i use it for test purpose and i forgot to push the new version.

2021-08-24 14:59 UTC, Giomaster commented
(DONT MAKE REVIEW) i found problems to push.

2021-08-25 20:39 UTC, Feggah requested changes
Checking the [GitHub API](https://docs.github.com/en/rest/reference/actions), the Repository Secret is in Actions group. IMHO the folder structure should be `actions/<...>`. For example:
- `apis/actions/v1alpha1/repositorysecret_types.go`
- `examples/actions/repositorysecret.yaml`
- `pkg/clients/actions/repositorysecret.go`
- `pkg/controller/actions/repositorysecret.go`

2021-08-25 20:39 UTC, Feggah commented on examples/secrets/secrets.yaml
> +kind: Repositorysecrets
Kubernetes uses `PascalCase` for kinds, so it should be `RepositorySecret` (in singular).

Here you can see some examples returned by `kubectl api-resources`:
<center>

![image](https://user-images.githubusercontent.com/11353912/130861944-01e0be60-0e48-4da1-bb58-4a885188e1ec.png)

</center>

2021-08-25 20:39 UTC, Feggah commented on pkg/clients/repositorysecrets/repositorysecrets.go
> +	sec, _, err := gh.GetRepoSecret(ctx, cr.Owner, cr.Repository, name)
If you already get the secret response from the API in the `gh.CreateOrUpdateRepoSecret`, why do you discard its value (using `_`) and make another request (`GET` in line 60) right after discarding the response?

I think it would be simpler if you just create `sec` with the returned value from the CreateOrUpdate request.

```suggestion
	if sec, err := gh.CreateOrUpdateRepoSecret(ctx, cr.Owner, cr.Repository, encryptedSecret); err != nil {
		return "", "", err
	}
```

2021-08-25 20:39 UTC, Feggah commented on pkg/controller/repositorysecrets/repositorysecrets.go
> +	cr.SetConditions(xpv1.Deleting())
You can remove this line, crossplane-runtime is already taking care of this for us, see this [link](https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L636).

2021-08-25 21:11 UTC, Giomaster commented on pkg/clients/repositorysecrets/repositorysecrets.go
> +	sec, _, err := gh.GetRepoSecret(ctx, cr.Owner, cr.Repository, name)
The function CreateOrUpdateRepoSecret returns only the status if the secret is created or updated with success. Otherwise, calling GetRepoSecret return more datas, like the time that repository secret updated recently. For more informations, please read [documentation](https://docs.github.com/en/rest/reference/actions#secrets).

2021-08-26 12:46 UTC, Feggah reviewed
Just two more nitpicks.

I have misinterpreted the behavior of the SDK in the method CreateOrUpdate, sorry for my reviews about it :)

2021-08-26 12:46 UTC, Feggah commented on examples/actions/secrets.yaml
> +kind: Repositorysecret
Sorry, I don't think I expressed myself well here. It wasn't just removing the plural, it needs to be `RepositorySecret`, not `Repositorysecret`.

2021-08-26 12:46 UTC, Feggah commented on pkg/controller/actions/repositorysecrets.go
> +	cr.SetConditions(xpv1.Deleting())
I think you forgot to remove this line.

2021-08-26 15:03 UTC, Feggah approved these changes
Looks pretty good @Giomaster ! Just added one more nitpick. After this, I will merge the PR.

Thanks! 🚀

2021-08-26 15:03 UTC, Feggah commented on apis/actions/v1alpha1/repositorysecrets_types.go
> +	LastUpdate string `json:"last_update,omitempty"`
Change this `snake_case` to `camelCase` (`encryptValue` and `lastUpdate`). I have pointed it out in [this comment](https://github.com/stone-payments/provider-github/pull/7#discussion_r694204738).

2021-08-26 15:35 UTC, Feggah requested changes
Sorry for my last approval, we may need to modify the code again. I was thinking in one use case and the CRD will not behave as expected.

If the user wants to "import" a secret (I know we can't import it, just create/update), this means that the CRD will update its value to which is defined in the K8S secret reference. But the problem is: the actual request will be an `UPDATE` (because the Repository Secret already exists in GitHub), but if you describe the resource, it will log that the resource have been `CREATED` (we expected it to be `UPDATED`).

This inconsistency is just a detail, but we must log properly to help investigating future issues. 

To fix it, we may need to change this code:
https://github.com/stone-payments/provider-github/blob/2679fce4f836ac2c91889ced5d0dcac798582bd5/pkg/controller/actions/repositorysecrets.go#L101-L104
To a `GET` request, then, the `IsUpToDate` will return `false` (because we will compare hashes from the K8S Secret and `Status` -- which will be empty).

With this false response from `IsUpToDate`, crossplane-runtime will call `Update()` instead of `Create()`. 

If the `GET` request doesn't find any secrets, thats because we need to create the secret.

Fixing this, the logs behavior will be fixed :)

The code will be something like this:
```golang
sec, _, err := gh.GetRepoSecret(ctx, cr.Spec.ForProvider.Owner, cr.Spec.ForProvider.Repository, meta.GetExternal(name))
if err != nil {
	return managed.ExternalObservation{}, errors.Wrap(err, "cannot get Secret")
}
```

You still can ignore the error returned by the GetRepoSecret if the response status code is 404, which just means that we need to create the resource.

## How to reproduce this issue
1. Create a secret in any repository in GitHub using the interface.
2. Apply the RepositorySecret manifest in Kubernetes with the same `external-name` as you defined in the step above.
3. `kubectl describe` the RepositorySecret.

You will see that the log will contain `CreatedExternalResource`, but it should be `UpdatedExternalResource`

2021-08-26 20:13 UTC, Feggah approved these changes
LGTM! Great work :)

2021-08-26 20:15 UTC, merged