[Draft] Add Repository "Content" kind.
stone-payments/provider-github pull request #8
Opened 2021-09-28 17:56 UTC by cnatan

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2021-10-19 03:47 UTC, Giomaster approved these changes

2021-10-19 04:56 UTC, Giomaster reviewed
The code sounds good! But i have some question: 

- General Scaffold
- Test Coverage
- Operator Behavior

### General Scaffold 
I think is more clean if the **repositories** service must be insert in a directory called **repository**. Ex:

- pkg
    - controller
        - repositories
            - content
                - content.go
                - content_test.go
            - repository  
                - repository.go
                - repository_test.go 

Would be nice move **fake** directory in _pkg/controller/repositories/content_ to _pkg/client/repositories/content_

### Test Coverage
Running the command `make reviewable test` show that accuracy of coverage is under 50% (40.9% of the statements). Should we care about this?

### Operator Behavior
In my functional test, the operator works to create and delete the content if `deletionPolicy` in _examples/repositories/content.yaml_ is set to **Orphan**. But delete dont works when `deletionPolicy` is set to **Delete**. Is this behavior expected?

2021-10-26 20:51 UTC, Feggah requested changes
Looks good in general, good job!

But I got confused on why did you need to delete the `Repository` managed resource implementation?

Besides that, please, follow the same `pkg` structure as official crossplane providers, for example, [provider-gcp](https://github.com/crossplane/provider-gcp/tree/master/pkg).

1. In the `controller` folder we don't need to nest folders, all `.go` files is going to be at the same level of the resource group that it belongs.
2. In the `clients` folder we should have each resource separated by its own folder. 

Finally but not least, is the definition of done of this managed resource just the option `reconcile: Disabled`? Because we are not checking for anything related to `Update` currently.

2021-10-26 20:51 UTC, Feggah commented on apis/repositories/v1alpha1/content_types.go
> +	Reconcile *string `json:"reconcile"`
```suggestion
	Reconcile *string `json:"reconcile,omitempty"`
```

2021-10-26 20:51 UTC, Feggah commented on apis/repositories/v1alpha1/content_types.go
> +	// +kubebuilder:validation:Enum=Enabled;Disabled
Should we give an `Enabled` option even if this resource isn't completely implemented? If the user sets it to `Enabled` and change the `spec.ForProvider.Content` it won't behave as expected.

I believe we should give this option if we have all controller methods properly implemented.

2021-10-26 20:51 UTC, Feggah commented on examples/repositories/content.yaml
> +  name: demo4
I would suggest you to change this name to `example` or something more representative.

2021-10-26 20:51 UTC, Feggah commented on pkg/clients/repositories/content/content.go
> +// Service defines the Repositories operations
```suggestion
// Service defines the Content operations
```

2021-10-27 16:01 UTC, Feggah approved these changes
LGTM (approving to remove my requested changes, but I would like to get some 👀 from others too)

2021-10-27 20:03 UTC, Quitanias commented on examples/repositories/content.yaml
> +  reconcile: Disabled
Should this option appear if it hasn't been implemented yet?

2021-10-27 20:39 UTC, Feggah commented on examples/repositories/content.yaml
> +  reconcile: Disabled
It has been implemented, check [this function](https://github.com/stone-payments/provider-github/blob/feature/custom-content/pkg/controller/repositories/content/content.go#L183)

2021-10-27 20:45 UTC, Quitanias commented on pkg/controller/repositories/content/content.go
> +	}
Shouldn't this function be inside the client folder?

2021-10-27 20:45 UTC, Quitanias commented on pkg/controller/repositories/content/content.go
> +}
Shouldn't this function be inside the client folder?

2021-10-28 13:00 UTC, Feggah commented on pkg/controller/repositories/content/content.go
> +	}
I don't know if this should be in the client folder... it has nothing related to the client itself, it is just a wrapper to the return type that we want. 

Actually we could simply remove this function and return it directly from the controller methods, but I don't see this as a problem to the code, for me it can stay as it is. Do you disagree?

2021-10-28 13:01 UTC, Feggah commented on pkg/controller/repositories/content/content.go
> +}
That is the same thing as my comment [above](https://github.com/stone-payments/provider-github/pull/8#discussion_r738365266).

2021-10-28 13:56 UTC, merged